2025-09-04T19:44:07.8974456Z ##[group]Run pytest tests/migrations/test_migration_roundtrip.py -q -m integration --cov=services --cov-append --cov-fail-under=0 -o addopts=''
2025-09-04T19:44:07.8975410Z [36;1mpytest tests/migrations/test_migration_roundtrip.py -q -m integration --cov=services --cov-append --cov-fail-under=0 -o addopts=''[0m
2025-09-04T19:44:07.9005805Z shell: /usr/bin/bash -e {0}
2025-09-04T19:44:07.9006034Z env:
2025-09-04T19:44:07.9006205Z   PG_USER: postgres
2025-09-04T19:44:07.9006409Z   PG_PASSWORD: pass
2025-09-04T19:44:07.9006598Z   PG_DATABASE: awa
2025-09-04T19:44:07.9006784Z   PG_HOST: localhost
2025-09-04T19:44:07.9006978Z   PG_PORT: 5432
2025-09-04T19:44:07.9007477Z   PG_SYNC_DSN: ***postgres:5432/awa
2025-09-04T19:44:07.9007900Z   PG_ASYNC_DSN: ***postgres:5432/awa
2025-09-04T19:44:07.9008290Z   DATABASE_URL: ***localhost:5432/awa
2025-09-04T19:44:07.9008528Z   DATA_DIR: /tmp/awa-data
2025-09-04T19:44:07.9008727Z   ENABLE_LIVE: 0
2025-09-04T19:44:07.9008904Z   TESTING: 1
2025-09-04T19:44:07.9009141Z   pythonLocation: /opt/hostedtoolcache/Python/3.11.13/x64
2025-09-04T19:44:07.9009581Z   PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.13/x64/lib/pkgconfig
2025-09-04T19:44:07.9009964Z   Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.13/x64
2025-09-04T19:44:07.9010309Z   Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.13/x64
2025-09-04T19:44:07.9010654Z   Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.13/x64
2025-09-04T19:44:07.9010999Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.13/x64/lib
2025-09-04T19:44:07.9011288Z ##[endgroup]
2025-09-04T19:44:09.0253008Z ImportError while loading conftest '/home/runner/work/AWA-App/AWA-App/tests/conftest.py'.
2025-09-04T19:44:09.0506243Z tests/conftest.py:28: in <module>
2025-09-04T19:44:09.0506841Z     from services.common.dsn import build_dsn
2025-09-04T19:44:09.0507372Z services/common/__init__.py:2: in <module>
2025-09-04T19:44:09.0507869Z     from .keepa import list_active_asins
2025-09-04T19:44:09.0508428Z services/common/keepa.py:3: in <module>
2025-09-04T19:44:09.0508936Z     from .dsn import build_dsn
2025-09-04T19:44:09.0509521Z E     File "/home/runner/work/AWA-App/AWA-App/services/common/dsn.py", line 37
2025-09-04T19:44:09.0510215Z E       netloc = f"{auth}{host}{":" + effective_port if effective_port else ''}"
2025-09-04T19:44:09.0510713Z E                                ^
2025-09-04T19:44:09.0511091Z E   SyntaxError: f-string: expecting '}'
2025-09-04T19:44:09.1562285Z ##[error]Process completed with exit code 4.
